#!/usr/bin/env sh


###
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# Sketchybar events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

# signals to center windows for ultrawide monitors 
yabai -m signal --add event=window_created action="bash ~/.config/yabai/center_windows_ultrawide_monitor.sh"
yabai -m signal --add event=window_destroyed action="bash ~/.config/yabai/center_windows_ultrawide_monitor.sh"
yabai -m signal --add event=space_changed action="bash ~/.config/yabai/center_windows_ultrawide_monitor.sh"

yabai -m config external_bar all:32:0

yabai -m config window_shadow off \
                window_border_blur off

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12 \
                bottom_padding 12 \
                left_padding 12 \
                right_padding 12 \
                window_gap 12

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap


# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off


